# Generated by Django 4.2.30 on 2026-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
