# Generated by Django 4.2.30 on 2026-09-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditiveReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sugar', 'Sugar'), ('oil', 'Oil'), ('refined_carb', 'Refined Carbohydrate'), ('whole_food', 'Whole Food'), ('additive', 'Additive'), ('preservative', 'Preservative'), ('colour', 'Colour'), ('flavour_enhancer', 'Flavour Enhancer'), ('salt_sodium', 'Salt / Sodium'), ('protein_source', 'Protein Source'), ('fiber_source', 'Fiber Source'), ('other', 'Other')], max_length=50)),
                ('fssai_ref', models.TextField(blank=True)),
                ('who_jecfa_ref', models.TextField(blank=True)),
                ('adi_mg_per_kg', models.FloatField(blank=True, null=True)),
                ('food_limit_mg_per_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('brands', models.CharField(blank=True, max_length=255)),
                ('ingredients_text', models.TextField(blank=True)),
                ('nutriments', models.JSONField(default=dict)),
                ('serving_size', models.CharField(blank=True, max_length=100)),
                ('serving_size_g', models.FloatField(blank=True, null=True)),
                ('product_weight_g', models.FloatField(blank=True, null=True)),
                ('categories_tags', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('off', 'Open Food Facts'), ('manual', 'Manual Entry')], default='off', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sugar', 'Sugar'), ('oil', 'Oil'), ('refined_carb', 'Refined Carbohydrate'), ('whole_food', 'Whole Food'), ('additive', 'Additive'), ('preservative', 'Preservative'), ('colour', 'Colour'), ('flavour_enhancer', 'Flavour Enhancer'), ('salt_sodium', 'Salt / Sodium'), ('protein_source', 'Protein Source'), ('fiber_source', 'Fiber Source'), ('other', 'Other')], max_length=50)),
                ('amount_g', models.FloatField(blank=True, null=True)),
                ('purpose_text', models.TextField(blank=True)),
                ('concern_text', models.TextField(blank=True)),
                ('regulatory_refs', models.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food_analysis.product')),
            ],
        ),
    ]
