from django.core.management.base import BaseCommand

from foodai_backend.food_analysis.models import AdditiveReference


ADDITIVES = [
    ("E100", "Curcumin", "colour", "", "", 0.0, None, "Turmeric-derived yellow colour; generally recognised as safe"),
    ("E101", "Riboflavin (Vitamin B2)", "colour", "", "", 0.5, None, "Vitamin B2 used as yellow colour; essential nutrient"),
    ("E102", "Tartrazine", "colour", "", "", 7.5, None, "Synthetic yellow azo dye; linked to hyperactivity in children"),
    ("E104", "Quinoline Yellow WS", "colour", "", "", 10.0, None, "Synthetic yellow-green colour; restricted in some foods"),
    ("E110", "Sunset Yellow FCF", "colour", "", "", 2.5, None, "Synthetic orange-yellow azo dye; ADHD concerns"),
    ("E120", "Cochineal / Carmine Acid", "colour", "", "", 0.0, None, "Red colour from insect extract; may cause allergy"),
    ("E122", "Azorubine / Carmoisine", "colour", "", "", 4.0, None, "Synthetic red azo dye; banned in some countries"),
    ("E123", "Amaranth", "colour", "", "", 1.5, None, "Synthetic red azo dye; restricted in many jurisdictions"),
    ("E124", "Ponceau 4R", "colour", "", "", 0.7, None, "Synthetic red azo colouring"),
    ("E127", "Erythrosine", "colour", "", "", 0.1, None, "Cherry-pink synthetic colour; iodine-containing"),
    ("E129", "Allura Red AC", "colour", "", "", 7.0, None, "Synthetic red azo dye; ADHD concerns in children"),
    ("E131", "Patent Blue V", "colour", "", "", 0.0, None, "Blue synthetic triarylmethane colour"),
    ("E132", "Indigo Carmine / Indigotine", "colour", "", "", 5.0, None, "Deep blue synthetic colour; widely used"),
    ("E133", "Brilliant Blue FCF", "colour", "", "", 6.0, None, "Bright blue synthetic colour; generally safe"),
    ("E140", "Chlorophylls and Chlorophyllins", "colour", "", "", 0.0, None, "Natural green colour from plants"),
    ("E141", "Copper complexes of chlorophylls", "colour", "", "", 15.0, None, "Stable green colour; copper-based"),
    ("E142", "Green S", "colour", "", "", 5.0, None, "Synthetic green colour; limited use"),
    ("E150a", "Plain Caramel", "colour", "", "", 0.0, None, "Caramel colour Class I; no ammonia or sulfite"),
    ("E150b", "Caustic Sulfite Caramel", "colour", "", "", 0.0, None, "Caramel colour Class II; sulfite process"),
    ("E150c", "Ammonia Caramel", "colour", "", "", 0.0, None, "Caramel colour Class III; ammonia process; 4-MEI concerns"),
    ("E150d", "Sulfite Ammonia Caramel", "colour", "", "", 0.0, None, "Caramel colour Class IV; cola colour; 4-MEI concerns"),
    ("E151", "Black PN / Brilliant Black BN", "colour", "", "", 1.0, None, "Synthetic black/brown colour"),
    ("E153", "Vegetable Carbon / Carbon Black", "colour", "", "", 0.0, None, "Black colour from vegetable char; banned in EU for kids"),
    ("E154", "Brown FK / Kipper Brown", "colour", "", "", 0.0, None, "Brown colour for kippers; restricted use"),
    ("E155", "Brown HT / Chocolate Brown", "colour", "", "", 3.0, None, "Synthetic brown azo dye"),
    ("E160a", "Alpha-, Beta-, Gamma-Carotenes", "colour", "", "", 0.0, None, "Natural orange-yellow colours; provitamin A"),
    ("E160b", "Annatto / Bixin / Norbixin", "colour", "", "", 0.0, None, "Yellow-orange colour from annatto seed"),
    ("E160c", "Paprika Extract / Capsanthin", "colour", "", "", 0.0, None, "Red-orange colour from paprika; spicy"),
    ("E160d", "Lycopene", "colour", "", "", 0.5, None, "Red colour from tomatoes; antioxidant"),
    ("E160e", "Beta-Apo-8'-Carotenal (C30)", "colour", "", "", 5.0, None, "Orange-red carotenoid colour"),
    ("E160f", "Ethyl ester of beta-apo-8'-carotenoic acid", "colour", "", "", 5.0, None, "Orange carotenoid colour"),
    ("E161b", "Lutein", "colour", "", "", 0.0, None, "Yellow xanthophyll; eye health nutrient"),
    ("E161g", "Canthaxanthin", "colour", "", "", 0.03, None, "Orange-red carotenoid; tanning pills risk"),
    ("E162", "Beetroot Red / Betanin", "colour", "", "", 0.0, None, "Natural red from beetroot; heat-sensitive"),
    ("E163", "Anthocyanins", "colour", "", "", 0.0, None, "Red-blue-purple colours from fruits"),
    ("E170", "Calcium Carbonate", "colour", "", "", 0.0, None, "White colour; also antacid/calcium supplement"),
    ("E171", "Titanium Dioxide", "colour", "", "", 0.0, None, "White opaque colour; EU banned as food additive 2022"),
    ("E172", "Iron Oxides and Hydroxides", "colour", "", "", 0.5, None, "Rust-brown/red/yellow/black colours"),
    ("E173", "Aluminium", "colour", "", "", 0.0, None, "Silver colour for decorations; not ingestible"),
    ("E174", "Silver", "colour", "", "", 0.0, None, "Metallic silver; decorative use only"),
    ("E175", "Gold", "colour", "", "", 0.0, None, "Metallic gold; decorative use only"),
    ("E180", "Pigment Rubine / Lithol Rubine BK", "colour", "", "", 0.0, None, "Red colour for cheese rind only"),
    ("E200", "Sorbic Acid", "preservative", "", "", 25.0, None, "Natural preservative from rowan berries; antifungal"),
    ("E201", "Sodium Sorbate", "preservative", "", "", 25.0, None, "Sodium salt of sorbic acid; water-soluble"),
    ("E202", "Potassium Sorbate", "preservative", "", "", 25.0, None, "Most widely used sorbate; very safe"),
    ("E203", "Calcium Sorbate", "preservative", "", "", 25.0, None, "Calcium salt of sorbic acid"),
    ("E210", "Benzoic Acid", "preservative", "", "", 5.0, None, "Naturally in berries; antifungal preservative"),
    ("E211", "Sodium Benzoate", "preservative", "", "", 5.0, None, "Sodium salt; benzene risk with vitamin C at low pH"),
    ("E212", "Potassium Benzoate", "preservative", "", "", 5.0, None, "Potassium salt of benzoic acid"),
    ("E213", "Calcium Benzoate", "preservative", "", "", 5.0, None, "Calcium salt of benzoic acid"),
    ("E214", "Ethylparaben (Ethyl p-Hydroxybenzoate)", "preservative", "", "", 10.0, None, "Paraben preservative; endocrine concerns"),
    ("E215", "Sodium Ethylparaben", "preservative", "", "", 10.0, None, "Sodium salt of ethylparaben"),
    ("E216", "Propylparaben", "preservative", "", "", 0.0, None, "Paraben; EU ban in foods for infants/kids"),
    ("E217", "Sodium Propylparaben", "preservative", "", "", 0.0, None, "Sodium salt of propylparaben"),
    ("E218", "Methylparaben", "preservative", "", "", 10.0, None, "Paraben preservative; long history of use"),
    ("E219", "Sodium Methylparaben", "preservative", "", "", 10.0, None, "Sodium salt of methylparaben"),
    ("E220", "Sulfur Dioxide", "preservative", "", "", 0.7, None, "Preservative/antioxidant; asthma trigger; sulfite sensitive"),
    ("E221", "Sodium Sulfite", "preservative", "", "", 0.7, None, "Sulfite preservative; browning inhibitor"),
    ("E222", "Sodium Hydrogen Sulfite / Bisulfite", "preservative", "", "", 0.7, None, "Sulfite salt; wine making"),
    ("E223", "Sodium Metabisulfite", "preservative", "", "", 0.7, None, "Sulfite; dried fruit/wine preservative"),
    ("E224", "Potassium Metabisulfite", "preservative", "", "", 0.7, None, "Potassium sulfite; Campden tablets for wine"),
    ("E225", "Potassium Sulfite", "preservative", "", "", 0.7, None, "Potassium sulfite salt"),
    ("E226", "Calcium Sulfite", "preservative", "", "", 0.7, None, "Calcium sulfite preservative"),
    ("E227", "Calcium Hydrogen Sulfite / Bisulfite", "preservative", "", "", 0.7, None, "Calcium bisulfite salt"),
    ("E228", "Potassium Hydrogen Sulfite / Bisulfite", "preservative", "", "", 0.7, None, "Potassium bisulfite salt"),
    ("E230", "Biphenyl / Diphenyl", "preservative", "", "", 0.0, None, "Fungicide for citrus peel; not for pulp; restricted"),
    ("E231", "Orthophenylphenol (OPP)", "preservative", "", "", 0.0, None, "Fungicide; citrus surface treatment"),
    ("E232", "Sodium Orthophenylphenol", "preservative", "", "", 0.0, None, "Sodium salt of OPP; post-harvest fungicide"),
    ("E233", "Thiabendazole (TBZ)", "preservative", "", "", 0.1, None, "Antifungal; banana/citrus peel treatment"),
    ("E234", "Nisin", "preservative", "", "", 12.5, None, "Antimicrobial peptide (bacteriocin); safe; cheese use"),
    ("E235", "Natamycin / Pimaricin", "preservative", "", "", 1.0, None, "Antifungal polyene; cheese/sausage surface"),
    ("E236", "Formic Acid", "preservative", "", "", 3.0, None, "Ant preservative; silage acidifier"),
    ("E237", "Sodium Formate", "preservative", "", "", 3.0, None, "Sodium salt of formic acid"),
    ("E238", "Calcium Formate", "preservative", "", "", 3.0, None, "Calcium salt of formic acid"),
    ("E239", "Hexamethylene Tetramine / Hexamine", "preservative", "", "", 0.15, None, "Formaldehyde releaser; cheese preservative"),
    ("E249", "Potassium Nitrite", "preservative", "", "", 0.07, None, "Curing salt; pink colour; botulism prevention; nitrosamine risk"),
    ("E250", "Sodium Nitrite", "preservative", "", "", 0.07, None, "Curing salt Prague Powder #1; cured meat pink colour"),
    ("E251", "Sodium Nitrate (Chile Saltpetre)", "preservative", "", "", 0.07, None, "Slow-release nitrite precursor; dry curing"),
    ("E252", "Potassium Nitrate (Saltpetre)", "preservative", "", "", 0.07, None, "Traditional saltpetre; dry cured meats"),
    ("E260", "Acetic Acid (Vinegar)", "preservative", "", "", 0.0, None, "Vinegar; natural preservative; pH control"),
    ("E261", "Potassium Acetate", "preservative", "", "", 0.0, None, "Potassium salt of acetic acid"),
    ("E262", "Sodium Acetates", "preservative", "", "", 0.0, None, "Sodium diacetate etc; bread anti-mould; salt&vinegar flavour"),
    ("E263", "Calcium Acetate", "preservative", "", "", 0.0, None, "Calcium salt; bakery mould inhibitor"),
    ("E264", "Ammonium Acetate", "preservative", "", "", 0.0, None, "Ammonium salt of acetic acid"),
    ("E270", "Lactic Acid", "preservative", "", "", 0.0, None, "Natural acid; fermented foods; pH adjuster"),
    ("E280", "Propionic Acid", "preservative", "", "", 0.0, None, "Bread mould inhibitor; Swiss cheese natural"),
    ("E281", "Sodium Propionate", "preservative", "", "", 0.0, None, "Sodium salt; bakery anti-mould"),
    ("E282", "Calcium Propionate", "preservative", "", "", 0.0, None, "Most common bakery preservative; E282 bread"),
    ("E283", "Potassium Propionate", "preservative", "", "", 0.0, None, "Potassium salt of propionic acid"),
    ("E284", "Boric Acid", "preservative", "", "", 0.0, None, "Caviar/sushi preservation; cumulative toxicity risk"),
    ("E285", "Sodium Tetraborate / Borax", "preservative", "", "", 0.0, None, "Borax; banned as food additive in many countries"),
    ("E290", "Carbon Dioxide (CO2)", "preservative", "", "", 0.0, None, "Carbonation; fizzy drinks; inert atmosphere"),
    ("E296", "Malic Acid", "preservative", "", "", 0.0, None, "Apple acid; acidulant; flavour enhancer"),
    ("E297", "Fumaric Acid", "preservative", "", "", 0.0, None, "Acidulant; sourdough; firming agent"),
    ("E300", "Ascorbic Acid (Vitamin C)", "additive", "", "", 0.0, None, "Vitamin C; antioxidant; browning inhibitor; essential"),
    ("E301", "Sodium Ascorbate", "additive", "", "", 0.0, None, "Sodium salt of vitamin C; more soluble"),
    ("E302", "Calcium Ascorbate", "additive", "", "", 0.0, None, "Calcium salt of vitamin C"),
    ("E303", "Potassium Ascorbate", "additive", "", "", 0.0, None, "Potassium salt of vitamin C"),
    ("E304", "Fatty Acid Esters of Ascorbic Acid", "additive", "", "", 0.0, None, "Ascorbyl palmitate/stearate; fat-soluble vitamin C"),
    ("E306", "Tocopherol-rich extract (natural Vitamin E)", "additive", "", "", 0.0, None, "Natural vitamin E; fat antioxidant"),
    ("E307", "Alpha-Tocopherol (synthetic)", "additive", "", "", 2.0, None, "Synthetic vitamin E; antioxidant"),
    ("E308", "Gamma-Tocopherol (synthetic)", "additive", "", "", 2.0, None, "Synthetic gamma-tocopherol; less active"),
    ("E309", "Delta-Tocopherol (synthetic)", "additive", "", "", 2.0, None, "Synthetic delta-tocopherol"),
    ("E310", "Propyl Gallate (PG)", "additive", "", "", 1.4, None, "Antioxidant; fats/oils; synergistic with BHA/BHT"),
    ("E311", "Octyl Gallate (OG)", "additive", "", "", 0.05, None, "Antioxidant for fats; limited use"),
    ("E312", "Dodecyl Gallate (DG)", "additive", "", "", 0.05, None, "Lauryl gallate; fat antioxidant"),
    ("E315", "Erythorbic Acid", "additive", "", "", 0.0, None, "Isoascorbic acid; antioxidant; cured meats"),
    ("E316", "Sodium Erythorbate", "additive", "", "", 0.0, None, "Sodium salt; cured meat colour fixative"),
    ("E319", "tert-Butylhydroquinone (TBHQ)", "additive", "", "", 0.7, None, "Strong phenolic antioxidant; oils/fats; debated safety"),
    ("E320", "Butylated Hydroxyanisole (BHA)", "additive", "", "", 0.5, None, "Antioxidant; IARC Group 2B (possible carcinogen)"),
    ("E321", "Butylated Hydroxytoluene (BHT)", "additive", "", "", 0.25, None, "Antioxidant; liver/kidney concerns at high dose"),
    ("E322", "Lecithin", "additive", "", "", 0.0, None, "Emulsifier; soy/egg/sunflower source; generally safe"),
    ("E325", "Sodium Lactate", "additive", "", "", 0.0, None, "Moisture retainer; pH control; shelf life extender"),
    ("E326", "Potassium Lactate", "additive", "", "", 0.0, None, "Potassium salt of lactic acid"),
    ("E327", "Calcium Lactate", "additive", "", "", 0.0, None, "Calcium supplement; cheese making; stabiliser"),
    ("E330", "Citric Acid", "additive", "", "", 0.0, None, "Lemon acid; most common acidulant; chelator; antioxidant"),
    ("E331", "Sodium Citrates", "additive", "", "", 0.0, None, "Mono/di/tri sodium citrate; buffer; anticoagulant"),
    ("E332", "Potassium Citrates", "additive", "", "", 0.0, None, "Potassium salts; kidney stone prevention in medicine"),
    ("E333", "Calcium Citrates", "additive", "", "", 0.0, None, "Calcium salts; food acid regulator; bioavailable calcium"),
    ("E334", "Tartaric Acid (L(+)-)", "additive", "", "", 0.0, None, "Grape/wine acid; sour taste; baking powder"),
    ("E335", "Sodium Tartrates", "additive", "", "", 0.0, None, "Sodium salts of tartaric acid"),
    ("E336", "Potassium Tartrates", "additive", "", "", 0.0, None, "Cream of tartar; baking; wine crystallisation"),
    ("E337", "Sodium Potassium Tartrate", "additive", "", "", 0.0, None, "Rochelle salt; buffer; laxative"),
    ("E338", "Phosphoric Acid", "additive", "", "", 0.0, None, "Cola acidulant; bone health concerns at high intake"),
    ("E339", "Sodium Phosphates", "additive", "", "", 70.0, None, "pH adjusters; emulsifiers; processed meats/cheese"),
    ("E340", "Potassium Phosphates", "additive", "", "", 70.0, None, "Potassium phosphate salts; similar uses"),
    ("E341", "Calcium Phosphates", "additive", "", "", 70.0, None, "Anti-caking; calcium fortification; leavening"),
    ("E343", "Magnesium Phosphates", "additive", "", "", 0.0, None, "Anti-caking; magnesium source"),
    ("E350", "Sodium Malates", "additive", "", "", 0.0, None, "Acidity regulators; malate salts"),
    ("E351", "Potassium Malate", "additive", "", "", 0.0, None, "Potassium malate salt"),
    ("E352", "Calcium Malates", "additive", "", "", 0.0, None, "Calcium malate; bioavailable calcium"),
    ("E355", "Adipic Acid", "additive", "", "", 5.0, None, "Acidulant; sour taste; nylon precursor; small amounts"),
    ("E356", "Sodium Adipate", "additive", "", "", 5.0, None, "Sodium salt of adipic acid"),
    ("E357", "Potassium Adipate", "additive", "", "", 5.0, None, "Potassium salt of adipic acid"),
    ("E363", "Succinic Acid", "additive", "", "", 0.0, None, "Acidulant; buffer; fermentation intermediate"),
    ("E365", "Sodium Fumarates", "additive", "", "", 0.0, None, "Sodium salts of fumaric acid"),
    ("E366", "Potassium Fumarate", "additive", "", "", 0.0, None, "Potassium salt of fumaric acid"),
    ("E367", "Calcium Fumarate", "additive", "", "", 0.0, None, "Calcium salt of fumaric acid"),
    ("E370", "1,4-Heptonolactone / Gamma-Heptalactone", "additive", "", "", 0.0, None, "Disputed; rarely used additive"),
    ("E375", "Niacin / Nicotinic Acid (Vitamin B3)", "additive", "", "", 0.0, None, "Vitamin B3; essential nutrient; fortification"),
    ("E380", "Triammonium Citrate", "additive", "", "", 0.0, None, "Emulsifier/salting-out agent; cheese"),
    ("E381", "Ammonium Ferric Citrate / Iron(III) Citrate", "additive", "", "", 0.0, None, "Iron fortification; colour development"),
    ("E385", "Calcium Disodium EDTA", "additive", "", "", 2.5, None, "Sequestrant/chelator; binds metal ions; rancidity prevention"),
    ("E392", "Extracts of Rosemary", "additive", "", "", 0.0, None, "Natural antioxidant; rosemary extract; carnosic acid"),
    ("E400", "Alginic Acid", "additive", "", "", 0.0, None, "Seaweed thickener/gelling agent; E-number 400"),
    ("E401", "Sodium Alginate", "additive", "", "", 0.0, None, "Sodium salt; spherification/caviar; thickener"),
    ("E402", "Potassium Alginate", "additive", "", "", 0.0, None, "Potassium salt of alginic acid"),
    ("E403", "Ammonium Alginate", "additive", "", "", 0.0, None, "Ammonium salt of alginic acid"),
    ("E404", "Calcium Alginate", "additive", "", "", 0.0, None, "Calcium salt; gel beads; wound dressing also"),
    ("E405", "Propylene Glycol Alginate (PGA)", "additive", "", "", 70.0, None, "Alginate ester; emulsifier/stabiliser"),
    ("E406", "Agar / Agar-Agar", "additive", "", "", 0.0, None, "Red seaweed gelatin substitute; vegan gelling"),
    ("E407", "Carrageenan", "additive", "", "", 0.0, None, "Red seaweed thickener; degraded vs undebated safety debate"),
    ("E407a", "Processed Eucheuma Seaweed (PES)", "additive", "", "", 0.0, None, "Semi-refined carrageenan; Philippines origin"),
    ("E410", "Locust Bean Gum (Carob Gum)", "additive", "", "", 0.0, None, "Carob seed gum; thickener/stabiliser; ice cream"),
    ("E412", "Guar Gum", "additive", "", "", 0.0, None, "Guar bean thickener; high fibre; gluten-free baking"),
    ("E413", "Tragacanth", "additive", "", "", 0.0, None, "Astragalus plant gum; emulsifier/thickener"),
    ("E414", "Acacia Gum / Gum Arabic", "additive", "", "", 0.0, None, "Acacia tree exudate; emulsifier; soft drinks; art glaze"),
    ("E415", "Xanthan Gum", "additive", "", "", 0.0, None, "Bacterial fermentation gum; gluten-free; stabiliser"),
    ("E416", "Karaya Gum / Indian Tragacanth", "additive", "", "", 0.0, None, "Sterculia tree gum; emulsifier/laxative"),
    ("E417", "Tara Gum / Peruvian Carob", "additive", "", "", 0.0, None, "Caesalpinia spinosa gum; similar to locust bean gum"),
    ("E418", "Gellan Gum", "additive", "", "", 0.0, None, "Sphingomonas bacterial gum; clear gels; plant-based milk"),
    ("E420", "Sorbitol and Sorbitol Syrup", "additive", "", "", 0.0, None, "Sugar alcohol/polyol; sweetener; laxative at high dose"),
    ("E421", "Mannitol", "additive", "", "", 0.0, None, "Sugar alcohol; cooling sweet taste; poorly absorbed"),
    ("E422", "Glycerol / Glycerin", "additive", "", "", 0.0, None, "Humectant/sweetener/solvent; biodiesel byproduct"),
    ("E425", "Konjac / Konjac Glucomannan", "additive", "", "", 0.0, None, "Elephant yam fibre; Shirataki noodles; thickener"),
    ("E428", "Gelatin", "additive", "", "", 0.0, None, "Animal collagen hydrolysate; gelling; not vegan/halal/kosher unless"),
    ("E430", "Polyoxyethylene (8) Stearate", "additive", "", "", 0.0, None, "Polysorbate-like emulsifier; limited use"),
    ("E431", "Polyoxyethylene (40) Stearate", "additive", "", "", 0.0, None, "PEG-40 stearate; emulsifier"),
    ("E432", "Polysorbate 20 / Tween 20", "additive", "", "", 10.0, None, "Emulsifier; ice cream; lab detergent use also"),
    ("E433", "Polysorbate 80 / Tween 80", "additive", "", "", 10.0, None, "Oleate ester emulsifier; ice cream; vaccine adjuvant also"),
    ("E434", "Polysorbate 40 / Tween 40", "additive", "", "", 10.0, None, "Palmitate; emulsifier"),
    ("E435", "Polysorbate 60 / Tween 60", "additive", "", "", 10.0, None, "Stearate; emulsifier; bakery"),
    ("E436", "Polysorbate 65 / Tween 65", "additive", "", "", 10.0, None, "Tristearate; emulsifier"),
    ("E440", "Pectins", "additive", "", "", 0.0, None, "Apple/citrus cell wall; jam gelling; soluble fibre"),
    ("E441", "Ammonium Phosphatides", "additive", "", "", 10.0, None, "Emulsifier; chocolate; replaces lecithin"),
    ("E442", "Ammonium Phosphatides", "additive", "", "", 10.0, None, "Same Y-species; cocoa butter emulsifier"),
    ("E445", "Glycerol Esters of Wood Rosins", "additive", "", "", 10.0, None, "Ester gum; chewing gum; beverage clouding"),
    ("E450", "Diphosphates (Pyrophosphates)", "additive", "", "", 70.0, None, "Leavening; water binding; processed cheese; meats"),
    ("E451", "Triphosphates", "additive", "", "", 70.0, None, "STPP etc; seafood/water retention"),
    ("E452", "Polyphosphates", "additive", "", "", 70.0, None, "Chain phosphates; emulsifiers; moisture retention"),
    ("E459", "Beta-Cyclodextrin", "additive", "", "", 5.0, None, "Cyclic oligosaccharide; flavour encapsulation"),
    ("E460", "Microcrystalline Cellulose / Cellulose Powder", "additive", "", "", 0.0, None, "Wood/cotton cellulose; anti-caking; pill filler"),
    ("E461", "Methyl Cellulose (MC)", "additive", "", "", 0.0, None, "Methyl ether cellulose; heat-set gel; vegan egg replacer"),
    ("E463", "Hydroxypropyl Cellulose (HPC)", "additive", "", "", 0.0, None, "Thickener; binder; pharma coatings"),
    ("E464", "Hydroxypropyl Methyl Cellulose (HPMC)", "additive", "", "", 0.0, None, "Hypromellose; heat gel; vegan capsules; gluten-free"),
    ("E465", "Ethyl Methyl Cellulose (EMC)", "additive", "", "", 0.0, None, "Surface-active cellulose ether; foam stabiliser"),
    ("E466", "Carboxy Methyl Cellulose (CMC)", "additive", "", "", 0.0, None, "Sodium CMC; thickener; toothpaste; gluten-free baking"),
    ("E468", "Cross-linked Sodium Carboxy Methyl Cellulose", "additive", "", "", 0.0, None, "Croscarmellose; pharma disintegrant"),
    ("E469", "Enzymatically hydrolysed Carboxy Methyl Cellulose", "additive", "", "", 0.0, None, "Lower viscosity CMC"),
    ("E470a", "Sodium, Potassium and Calcium Salts of Fatty Acids", "additive", "", "", 0.0, None, "Emulsifiers; soap-like; anti-caking"),
    ("E470b", "Magnesium Salts of Fatty Acids", "additive", "", "", 0.0, None, "Magnesium stearate etc; pharma lubricant"),
    ("E471", "Mono- and Diglycerides of Fatty Acids", "additive", "", "", 0.0, None, "Most common emulsifier; bakery/ice cream/margarine"),
    ("E472a", "Acetic Acid Esters of Mono- and Diglycerides (ACETEM)", "additive", "", "", 0.0, None, "Acetylated monoglycerides; aerated goods"),
    ("E472b", "Lactic Acid Esters of Mono- and Diglycerides (LACTEM)", "additive", "", "", 0.0, None, "Lactylated; bread softener; cakes"),
    ("E472c", "Citric Acid Esters of Mono- and Diglycerides (CITREM)", "additive", "", "", 0.0, None, "Citrem; margarine; emulsifier"),
    ("E472d", "Tartaric Acid Esters of Mono- and Diglycerides (DATEM)", "additive", "", "", 0.0, None, "DATEM; bread dough strengthener; high-rising"),
    ("E472e", "Diacetyltartaric Acid Esters of Mono- and Diglycerides", "additive", "", "", 0.0, None, "Same as DATEM; diacetyl tartaric"),
    ("E472f", "Mixed Acetic and Tartaric Acid Esters", "additive", "", "", 0.0, None, "Mixed acetate tartrate esters"),
    ("E473", "Sucrose Esters of Fatty Acids", "additive", "", "", 10.0, None, "Sugar esters; HLB-tunable emulsifiers"),
    ("E474", "Sucroglycerides", "additive", "", "", 10.0, None, "Transesterified sucrose + glycerides"),
    ("E475", "Polyglycerol Esters of Fatty Acids (PGE)", "additive", "", "", 0.0, None, "Polyglycerol esters; cake batters; whipped cream"),
    ("E476", "Polyglycerol Polyricinoleate (PGPR)", "additive", "", "", 7.5, None, "Castor-oil based; chocolate flow improver"),
    ("E477", "Propane-1,2-diol Esters of Fatty Acids (PGMS)", "additive", "", "", 0.0, None, "Propylene glycol monostearate; cake emulsifier"),
    ("E478", "Lactylated Fatty Acid Esters of Glycerol and Propane-1,2-diol", "additive", "", "", 0.0, None, "Complex lactylated emulsifier blend"),
    ("E479b", "Thermally Oxidised Soya Bean Oil Inter-esterified", "additive", "", "", 0.0, None, "E479b; bread improver; restricted"),
    ("E481", "Sodium Stearoyl-2-Lactylate (SSL)", "additive", "", "", 20.0, None, "Bread dough conditioner; soft crumb; extends shelf life"),
    ("E482", "Calcium Stearoyl-2-Lactylate (CSL)", "additive", "", "", 20.0, None, "Calcium salt; dough strengthener"),
    ("E483", "Stearyl Tartrate", "additive", "", "", 0.0, None, "Surface-active; emulsifier"),
    ("E491", "Sorbitan Monostearate (Span 60)", "additive", "", "", 0.0, None, "Lipophilic emulsifier; Span 60"),
    ("E492", "Sorbitan Tristearate (Span 65)", "additive", "", "", 0.0, None, "Span 65; tristearate"),
    ("E493", "Sorbitan Monolaurate (Span 20)", "additive", "", "", 0.0, None, "Span 20; laurate ester"),
    ("E494", "Sorbitan Monooleate (Span 80)", "additive", "", "", 0.0, None, "Span 80; oleate; lipophilic"),
    ("E495", "Sorbitan Monopalmitate (Span 40)", "additive", "", "", 0.0, None, "Span 40; palmitate"),
    ("E500", "Sodium Carbonates (Soda Ash, Bicarb)", "additive", "", "", 0.0, None, "Baking soda (E500ii); leavening; alkaline"),
    ("E501", "Potassium Carbonates", "additive", "", "", 0.0, None, "Potash; cocoa alkalisation Dutch process"),
    ("E503", "Ammonium Carbonates", "additive", "", "", 0.0, None, "Baker's ammonia; crisp cookies; releases ammonia gas"),
    ("E504", "Magnesium Carbonates", "additive", "", "", 0.0, None, "Anti-caking; magnesium source; antacid"),
    ("E507", "Hydrochloric Acid (HCl)", "additive", "", "", 0.0, None, "Gastric juice also; pH control; food grade"),
    ("E508", "Potassium Chloride", "additive", "", "", 0.0, None, "Salt substitute; LoSalt; KCl; kidney risk for CKD"),
    ("E509", "Calcium Chloride", "additive", "", "", 0.0, None, "Firming agent; cheese curd; tofu coagulant; de-icer also"),
    ("E510", "Ammonium Chloride", "additive", "", "", 0.0, None, "Sal ammoniac; salty liquorice; yeast nutrient"),
    ("E511", "Magnesium Chloride", "additive", "", "", 0.0, None, "Nigari; tofu coagulant; Mg source"),
    ("E512", "Stannous Chloride / Tin(II) Chloride", "additive", "", "", 0.0, None, "Colour retention; canned asparagus; tin salt"),
    ("E513", "Sulfuric Acid", "additive", "", "", 0.0, None, "Acid; pH adjustment; invert sugar; car battery acid too"),
    ("E514", "Sodium Sulfates", "additive", "", "", 0.0, None, "Glauber's salt; laxative; rarely used"),
    ("E515", "Potassium Sulfates", "additive", "", "", 0.0, None, "Potassium sulfate; fertiliser grade vs food"),
    ("E516", "Calcium Sulfate (Gypsum)", "additive", "", "", 0.0, None, "Gypsum; plaster of Paris also; tofu coagulant; calcium"),
    ("E517", "Ammonium Sulfate", "additive", "", "", 0.0, None, "Yeast food; bread improver; fertiliser"),
    ("E518", "Magnesium Sulfate (Epsom Salt)", "additive", "", "", 0.0, None, "Epsom salts; laxative; magnesium source; bath soak"),
    ("E519", "Copper(II) Sulfate", "additive", "", "", 0.0, None, "Trace; colour fixative; anti-fungal; Bordeaux mix origin"),
    ("E520", "Aluminium Sulfate", "additive", "", "", 0.0, None, "Alum; pickling crispness; water coagulant; aluminium concern"),
    ("E521", "Aluminium Sodium Sulfate", "additive", "", "", 0.0, None, "Soda alum; baking acid; slow-acting leavening"),
    ("E522", "Aluminium Potassium Sulfate (Potash Alum)", "additive", "", "", 0.0, None, "Potash alum; pickling; deodorant; aftershave block"),
    ("E523", "Aluminium Ammonium Sulfate (Ammonium Alum)", "additive", "", "", 0.0, None, "Ammonium alum; baking powder component"),
    ("E524", "Sodium Hydroxide (Lye / Caustic Soda)", "additive", "", "", 0.0, None, "Lye; pretzels/soap; pH adjust; corrosive; food grade only"),
    ("E525", "Potassium Hydroxide (Caustic Potash)", "additive", "", "", 0.0, None, "Caustic potash; pH adjuster; soap making"),
    ("E526", "Calcium Hydroxide (Slaked Lime / Pickling Lime)", "additive", "", "", 0.0, None, "Lime water; pickling; corn nixtamalization; mortar"),
    ("E527", "Ammonium Hydroxide", "additive", "", "", 0.0, None, "Ammonia solution; pH adjuster; antimicrobial"),
    ("E528", "Magnesium Hydroxide (Milk of Magnesia)", "additive", "", "", 0.0, None, "Antacid/laxative; pH adjuster"),
    ("E529", "Calcium Oxide (Quicklime / Burnt Lime)", "additive", "", "", 0.0, None, "Quicklime; exothermic with water; drying agent"),
    ("E530", "Magnesium Oxide", "additive", "", "", 0.0, None, "Anti-caking; magnesium supplement; antacid"),
    ("E535", "Sodium Ferrocyanide", "additive", "", "", 20.0, None, "Anti-caking; table salt; low toxicity; cyanide not released at pH 7"),
    ("E536", "Potassium Ferrocyanide", "additive", "", "", 20.0, None, "Yellow prussiate of potash; salt anti-caking"),
    ("E537", "Ferrous Hexacyanoferrate II", "additive", "", "", 20.0, None, "Iron blue; anti-caking for salt"),
    ("E538", "Calcium Ferrocyanide", "additive", "", "", 20.0, None, "Calcium hexacyanoferrate; salt anti-caking"),
    ("E540", "Dicalcium Diphosphate", "additive", "", "", 70.0, None, "Anti-caking; calcium phosphate"),
    ("E541", "Sodium Aluminium Phosphate (SALP)", "additive", "", "", 0.0, None, "Acidic baking powder leavening; aluminium-free trend"),
    ("E542", "Bone Phosphate (Essentially Calcium Phosphate)", "additive", "", "", 70.0, None, "Anti-caking; bone meal source"),
    ("E544", "Calcium Polyphosphates", "additive", "", "", 70.0, None, "Anti-caking; emulsifier"),
    ("E545", "Ammonium Polyphosphate", "additive", "", "", 70.0, None, "Yeast nutrient; emulsifier"),
    ("E551", "Silicon Dioxide (Silica / Fumed Silica)", "additive", "", "", 0.0, None, "Sand/quartz; anti-caking; E551; nano form debated"),
    ("E552", "Calcium Silicate", "additive", "", "", 0.0, None, "Anti-caking; salt/flour; absorbent"),
    ("E553a", "Magnesium Silicate / Talc", "additive", "", "", 0.0, None, "Talc; anti-caking; asbestos-free grade only"),
    ("E553b", "Talc (Magnesium Silicate)", "additive", "", "", 0.0, None, "Same talc; E553b; rice anti-sticking coating"),
    ("E554", "Sodium Aluminosilicate (Sodium Silicoaluminate)", "additive", "", "", 0.0, None, "Anti-caking; aluminium-containing salt"),
    ("E555", "Potassium Aluminium Silicate", "additive", "", "", 0.0, None, "Anti-caking; feldspar-like"),
    ("E556", "Calcium Aluminosilicate", "additive", "", "", 0.0, None, "Anti-caking; aluminium calcium silicate"),
    ("E557", "Zinc Silicate", "additive", "", "", 0.0, None, "Anti-caking; rarely used"),
    ("E558", "Bentonite", "additive", "", "", 0.0, None, "Clay; wine/beer fining; detox supplement claims"),
    ("E559", "Aluminium Silicate (Kaolin)", "additive", "", "", 0.0, None, "Kaolin clay; anti-caking; diarrhoea remedy; porcelain"),
    ("E560", "Potassium Silicate", "additive", "", "", 0.0, None, "Anti-caking; silicate salt"),
    ("E561", "Sodium Silicate", "additive", "", "", 0.0, None, "Waterglass; egg preservative; detergent builder"),
    ("E562", "Magnesium Trisilicate", "additive", "", "", 0.0, None, "Antacid; anti-caking"),
    ("E563", "Magnesium Silicate (Synthetic)", "additive", "", "", 0.0, None, "Synthetic magnesium silicate"),
    ("E570", "Stearic Acid", "additive", "", "", 0.0, None, "Fatty acid; lubricant/anti-caking; soap/candles too"),
    ("E572", "Magnesium Stearate / Calcium Stearate", "additive", "", "", 0.0, None, "Pill lubricant; anti-caking; soap source"),
    ("E574", "Glucono-delta-Lactone (GDL)", "additive", "", "", 0.0, None, "GDL; slow acid release; silken tofu coagulant; sourdough"),
    ("E575", "Glucono-delta-Lactone (GDL)", "additive", "", "", 0.0, None, "Same E575; duplicate listing sometimes"),
    ("E576", "Sodium Gluconate", "additive", "", "", 0.0, None, "Chelator; sodium salt of gluconic acid"),
    ("E577", "Potassium Gluconate", "additive", "", "", 0.0, None, "Potassium supplement; chelator"),
    ("E578", "Calcium Gluconate", "additive", "", "", 0.0, None, "IV calcium also; calcium fortification; antidote for hydrofluoric"),
    ("E579", "Ferrous Gluconate (Iron(II) Gluconate)", "additive", "", "", 0.0, None, "Iron supplement; anaemia; olive colour blackening"),
    ("E580", "Magnesium Gluconate", "additive", "", "", 0.0, None, "Magnesium supplement; bioavailable"),
    ("E585", "Ferrous Lactate (Iron(II) Lactate)", "additive", "", "", 0.0, None, "Iron fortification; olive blackening"),
    ("E586", "4-Hexylresorcinol", "additive", "", "", 1.0, None, "Anti-browning; shrimp/fruit; prevents melanosis"),
    ("E620", "Glutamic Acid", "flavour_enhancer", "", "", 0.0, None, "Umami amino acid; free glutamic acid; protein component"),
    ("E621", "Monosodium Glutamate (MSG)", "flavour_enhancer", "", "", 0.0, None, "Umami salt; Chinese restaurant syndrome myth debunked; GRAS"),
    ("E622", "Monopotassium Glutamate", "flavour_enhancer", "", "", 0.0, None, "Potassium salt of glutamic acid"),
    ("E623", "Calcium Diglutamate", "flavour_enhancer", "", "", 0.0, None, "Calcium salt; umami enhancer"),
    ("E624", "Monoammonium Glutamate", "flavour_enhancer", "", "", 0.0, None, "Ammonium glutamate salt"),
    ("E625", "Magnesium Diglutamate", "flavour_enhancer", "", "", 0.0, None, "Magnesium salt of glutamic acid"),
    ("E626", "Guanylic Acid (GMP)", "flavour_enhancer", "", "", 0.0, None, "5'-Guanylic acid; nucleotide; synergistic umami"),
    ("E627", "Disodium 5'-Guanylate (GMP-Na2)", "flavour_enhancer", "", "", 0.0, None, "Disodium guanylate; yeast/sardine extract; with MSG"),
    ("E628", "Dipotassium 5'-Guanylate", "flavour_enhancer", "", "", 0.0, None, "Potassium GMP salt"),
    ("E629", "Calcium 5'-Guanylate", "flavour_enhancer", "", "", 0.0, None, "Calcium GMP salt"),
    ("E630", "Inosinic Acid (IMP)", "flavour_enhancer", "", "", 0.0, None, "5'-Inosinic acid; nucleotide umami"),
    ("E631", "Disodium 5'-Inosinate (IMP-Na2)", "flavour_enhancer", "", "", 0.0, None, "Disodium inosinate; bonito/tuna source; umami booster"),
    ("E632", "Dipotassium 5'-Inosinate", "flavour_enhancer", "", "", 0.0, None, "Potassium IMP salt"),
    ("E633", "Calcium 5'-Inosinate", "flavour_enhancer", "", "", 0.0, None, "Calcium IMP salt"),
    ("E634", "Calcium 5'-Ribonucleotides", "flavour_enhancer", "", "", 0.0, None, "Calcium mixed 5'-nucleotides"),
    ("E635", "Disodium 5'-Ribonucleotides (I+G)", "flavour_enhancer", "", "", 0.0, None, "50:50 IMP+GMP; ultra umami; instant noodles"),
    ("E636", "Maltol", "flavour_enhancer", "", "", 2.0, None, "Sweet caramel aroma enhancer; bread/baked goods"),
    ("E637", "Ethyl Maltol", "flavour_enhancer", "", "", 5.0, None, "Stronger than maltol; candy/fruity sweetness boost"),
    ("E640", "Glycine and its Sodium Salt", "flavour_enhancer", "", "", 0.0, None, "Amino acid sweetener; protein building block"),
    ("E650", "Zinc Acetate", "flavour_enhancer", "", "", 0.0, None, "Zinc supplement; lozenge; taste modifier"),
    ("E900", "Polydimethylsiloxane (Dimethylpolysiloxane)", "additive", "", "", 10.0, None, "Silicone anti-foam; frying oil; silly putty same polymer"),
    ("E901", "Beeswax (White and Yellow)", "additive", "", "", 0.0, None, "Honeycomb wax; glazing; chewing gum; candles"),
    ("E902", "Candelilla Wax", "additive", "", "", 0.0, None, "Desert plant wax; candy/chocolate glaze; vegan"),
    ("E903", "Carnauba Wax", "additive", "", "", 0.0, None, "Brazil palm 'queen of waxes'; car polish also; glossy food glaze"),
    ("E904", "Shellac", "additive", "", "", 0.0, None, "Lac bug resin; confectioner's glaze; wood finish; not vegan"),
    ("E905", "Microcrystalline Wax", "additive", "", "", 0.0, None, "Petroleum wax; cheese coating; packaging"),
    ("E907", "Crystalline Wax", "additive", "", "", 0.0, None, "Paraffin-like crystalline coating"),
    ("E912", "Montanic Acid Esters", "additive", "", "", 0.0, None, "Lignite wax esters; fruit coating"),
    ("E913", "Lanolin / Wool Fat", "additive", "", "", 0.0, None, "Sheep wool grease; fruit coating; skin cream; not vegan"),
    ("E914", "Oxidised Polyethylene Wax", "additive", "", "", 0.0, None, "PE wax; citrus fruit coating"),
    ("E920", "L-Cysteine Hydrochloride", "additive", "", "", 0.0, None, "Flour improver; reduces dough mixing time; hair/feather source"),
    ("E921", "L-Cysteine", "additive", "", "", 0.0, None, "Free amino acid; similar dough conditioner"),
    ("E922", "Potassium Persulfate", "additive", "", "", 0.0, None, "Flour maturing agent; hair bleach oxidiser; restricted"),
    ("E923", "Ammonium Persulfate", "additive", "", "", 0.0, None, "Flour improver; oxidiser"),
    ("E924a", "Potassium Bromate", "additive", "", "", 0.0, None, "Banned as carcinogen (IARC 2B); residual in bread; avoid"),
    ("E924b", "Calcium Bromate", "additive", "", "", 0.0, None, "Also banned; similar to potassium bromate"),
    ("E925", "Chlorine", "additive", "", "", 0.0, None, "Flour bleaching; cake flour; drinking water disinfectant"),
    ("E926", "Chlorine Dioxide", "additive", "", "", 0.0, None, "Flour bleacher/maturing agent; gas; also kills viruses"),
    ("E927b", "Carbamide / Urea", "additive", "", "", 0.0, None, "Yeast food; pretzel browning; fertiliser; body waste product"),
    ("E928", "Benzoyl Peroxide", "additive", "", "", 40.0, None, "Flour bleach; acne cream oxidiser same"),
    ("E930", "Calcium Peroxide", "additive", "", "", 100.0, None, "Flour bleaching/improving; slow oxygen release"),
    ("E938", "Argon", "additive", "", "", 0.0, None, "Inert gas; wine/snack packaging; replaces oxygen"),
    ("E939", "Helium", "additive", "", "", 0.0, None, "Inert gas; balloons also; packaging rarely"),
    ("E940", "Dichlorodifluoromethane (CFC-12)", "additive", "", "", 0.0, None, "Ozone-depleting CFC; banned Montreal Protocol; historical"),
    ("E941", "Nitrogen (N2)", "additive", "", "", 0.0, None, "Inert atmosphere; chip bags; draught Guinness widget"),
    ("E942", "Nitrous Oxide (Laughing Gas)", "additive", "", "", 0.0, None, "Cream chargers; whipped cream aerosol; dental anaesthetic"),
    ("E943a", "Butane", "additive", "", "", 0.0, None, "Aerosol propellant; cigarette lighter fuel; very limited"),
    ("E943b", "Isobutane", "additive", "", "", 0.0, None, "Aerosol propellant; butane isomer"),
    ("E944", "Propane", "additive", "", "", 0.0, None, "Aerosol propellant; BBQ gas; restricted food use"),
    ("E948", "Oxygen", "additive", "", "", 0.0, None, "Modified atmosphere packaging; red meat colour preservation"),
    ("E949", "Hydrogen", "additive", "", "", 0.0, None, "Hydrogenation reactant; margarine/shortening production"),
    ("E950", "Acesulfame K (Ace-K)", "additive", "", "", 15.0, None, "Non-nutritive sweetener; 200x sugar; blends with sucralose/aspartame"),
    ("E951", "Aspartame", "additive", "", "", 40.0, None, "NutraSweet/Equal; phenylalanine warning PKU; 200x sugar; debated"),
    ("E952", "Cyclamic Acid / Cyclamates", "additive", "", "", 7.0, None, "Sodium cyclamate; banned US 1969; legal EU; 30x sugar"),
    ("E953", "Isomalt", "additive", "", "", 0.0, None, "Sugar alcohol/polyol; low GI; dental friendly; sugar-free candies"),
    ("E954", "Saccharin", "additive", "", "", 2.5, None, "Sweet'N Low; oldest artificial sweetener 400x; cancer label removed"),
    ("E955", "Sucralose", "additive", "", "", 5.0, None, "Splenda; 600x sugar; chlorinated sucrose; most stable; baking safe"),
    ("E956", "Alitame", "additive", "", "", 1.0, None, "Aclame; 2000x sugar; not approved US/EU; some countries"),
    ("E957", "Thaumatin", "additive", "", "", 0.0, None, "Katemfe fruit protein; 2000x sugar; flavour modifier; not sweet bulk"),
    ("E959", "Neohesperidin DC", "additive", "", "", 15.0, None, "Bitter orange flavanone; 1500x sweet aftertaste; bitter blocker"),
    ("E960", "Steviol Glycosides (Stevia)", "additive", "", "", 4.0, None, "Stevia leaf; Reb-A/D/M; 200-300x; natural zero-cal"),
    ("E961", "Neotame", "additive", "", "", 2.0, None, "NutraSweet relative; 8000x sugar; no PKU issue; not widely used"),
    ("E962", "Salt of Aspartame-Acesulfame K (Twinsweet)", "additive", "", "", 0.0, None, "Combination salt; synergistic sweet"),
    ("E963", "Advantame", "additive", "", "", 5.0, None, "20000x sugar; aspartame derivative; no PKU limit; EU/US approved"),
    ("E965", "Maltitol and Maltitol Syrup", "additive", "", "", 0.0, None, "Sugar alcohol; 90% sweetness; lower glycaemic; laxative large"),
    ("E966", "Lactitol", "additive", "", "", 0.0, None, "Milk sugar alcohol; sugar-free candy; laxative; colonoscopy prep"),
    ("E967", "Xylitol", "additive", "", "", 0.0, None, "Birch sugar; dental prevents cavities; DEADLY to dogs; sugar alcohol"),
    ("E968", "Erythritol", "additive", "", "", 0.0, None, "Zero-cal sugar alcohol; 70% sweet; no laxative; cooling; CVD debate"),
    ("E969", "Advantame", "additive", "", "", 5.0, None, "Re-listing; same E963; newer intense sweetener"),
    ("E999", "Quillaia Extract", "additive", "", "", 0.0, None, "Soapbark saponins; foam enhancer; soda/root beer; vaccine adjuvant"),
    ("INS1100", "Polylysine", "preservative", "", "", 6.25, None, "Antimicrobial peptide; Streptomyces; sushi/noodle preservative"),
    ("INS2344", "Polydextrose", "fiber_source", "", "", 0.0, None, "Synthetic soluble fibre; low-cal bulking; prebiotic claims"),
    ("INS1200", "Inulin", "fiber_source", "", "", 0.0, None, "Chicory root fructan; prebiotic soluble fibre; FODMAP bloating"),
    ("INS1201", "Oligofructose", "fiber_source", "", "", 0.0, None, "Short-chain inulin; prebiotic; sweet taste"),
    ("INS1202", "Guar Fiber", "fiber_source", "", "", 0.0, None, "Partially hydrolysed guar gum PHGG; soluble fibre"),
    ("INS1203", "Psyllium Husk Fiber", "fiber_source", "", "", 0.0, None, "Plantago ovata; soluble mucilage; Metamucil; cholesterol lower"),
    ("INS1204", "Beta-Glucan", "fiber_source", "", "", 0.0, None, "Oat/barley fibre; heart health (FDA claim); soluble"),
    ("INS1205", "Arabinoxylan", "fiber_source", "", "", 0.0, None, "Cereal bran hemicellulose; soluble fibre"),
    ("INS1300", "Whey Protein Isolate", "protein_source", "", "", 0.0, None, "Dairy WPI; complete protein; leucine high; sports nutrition"),
    ("INS1301", "Whey Protein Concentrate", "protein_source", "", "", 0.0, None, "WPC 70-80% protein; lactose remaining"),
    ("INS1302", "Soy Protein Isolate", "protein_source", "", "", 0.0, None, "Soy SPI; 90% protein; complete plant protein"),
    ("INS1303", "Pea Protein Isolate", "protein_source", "", "", 0.0, None, "Yellow pea; plant-based; lysine high; iron"),
    ("INS1304", "Rice Protein Isolate", "protein_source", "", "", 0.0, None, "Brown rice protein; hypoallergenic; low lysine"),
    ("INS1305", "Hemp Protein", "protein_source", "", "", 0.0, None, "Cannabis sativa seed; complete; omega 3&6; fibre"),
    ("INS1400", "Sugar (Sucrose)", "sugar", "", "", 0.0, None, "Table sugar; cane/beet; fructose+glucose; 4 kcal/g"),
    ("INS1401", "High Fructose Corn Syrup", "sugar", "", "", 0.0, None, "HFCS 42/55; corn starch; liver fructose metabolism debate"),
    ("INS1402", "Glucose Syrup", "sugar", "", "", 0.0, None, "Corn syrup; glucose polymers; confectionery"),
    ("INS1403", "Fructose (Crystalline)", "sugar", "", "", 0.0, None, "Fruit sugar; sweetest natural sugar; 1.7x sucrose"),
    ("INS1404", "Dextrose (Glucose)", "sugar", "", "", 0.0, None, "Glucose; grape sugar; IV sugar; 0.7x sucrose sweetness"),
    ("INS1405", "Brown Sugar", "sugar", "", "", 0.0, None, "Sucrose + molasses; 95% sugar same as white"),
    ("INS1406", "Coconut Sugar", "sugar", "", "", 0.0, None, "Coconut palm nectar; inulin; still 78% sucrose; low GI claim"),
    ("INS1407", "Maple Syrup", "sugar", "", "", 0.0, None, "Sap of sugar maple; sucrose ~66%; minerals + antioxidants"),
    ("INS1408", "Honey", "sugar", "", "", 0.0, None, "Bee nectar; glucose+fructose; infant botulism <1yr; Wound care medical"),
    ("INS1409", "Agave Syrup / Nectar", "sugar", "", "", 0.0, None, "Agave plant; 55-90% fructose; marketed low GI but high fructose"),
    ("INS1410", "Rice Syrup / Brown Rice Syrup", "sugar", "", "", 0.0, None, "Enzyme hydrolysed rice; glucose/maltose; arsenic trace concern"),
    ("INS1500", "Refined Wheat Flour (Maida)", "refined_carb", "", "", 0.0, None, "Endosperm only; fibre removed; high GI; white bread"),
    ("INS1501", "White Rice (Polished)", "refined_carb", "", "", 0.0, None, "Bran+germ removed; B6/arsenic; white rice low fibre"),
    ("INS1502", "Cornstarch / Maize Starch", "refined_carb", "", "", 0.0, None, "Endosperm starch; thickener; 100% glucose polymer"),
    ("INS1503", "Tapioca Starch / Cassava Starch", "refined_carb", "", "", 0.0, None, "Cassava/manioc; neutral thickener; cyanide removed"),
    ("INS1504", "Potato Starch", "refined_carb", "", "", 0.0, None, "Tuber starch; retrograde; cold-water swelling"),
    ("INS1505", "Arrowroot Starch", "refined_carb", "", "", 0.0, None, "Maranta arundinacea; fine starch; infant foods historic"),
    ("INS1506", "Instant Noodles (Refined Wheat)", "refined_carb", "", "", 0.0, None, "Fried/air dried wheat noodles; high sodium+palmoil"),
    ("INS1507", "White Bread", "refined_carb", "", "", 0.0, None, "White flour; high GI; low fibre; enriched micronutrients"),
    ("INS1508", "Pastries / Croissants (Refined)", "refined_carb", "", "", 0.0, None, "White flour + butter/shortening; layered; trans fat"),
    ("INS1600", "Olive Oil (Virgin/Extra Virgin)", "oil", "", "", 0.0, None, "Olea europaea; monounsaturated oleic 70%; Mediterranean diet"),
    ("INS1601", "Canola Oil / Rapeseed", "oil", "", "", 0.0, None, "Low erucic acid; omega-3 ALA 10%; high MUFA; neutral flavour"),
    ("INS1602", "Sunflower Oil", "oil", "", "", 0.0, None, "High linoleic (PUFA); high oleic variants exist; vitamin E"),
    ("INS1603", "Palm Oil", "oil", "", "", 0.0, None, "Elaeis guineensis; 50% saturated; orangutan deforestation; heat stable"),
    ("INS1604", "Coconut Oil (Virgin/Refined)", "oil", "", "", 0.0, None, "92% saturated (lauric); LDL raise debate; MCT rich fraction"),
    ("INS1605", "Soybean Oil", "oil", "", "", 0.0, None, "Most produced oil; omega-6 PUFA; hydrogenated to shortenings"),
    ("INS1606", "Peanut Oil", "oil", "", "", 0.0, None, "High smoke point; peanut allergen; MUFA/PUFA mix"),
    ("INS1607", "Sesame Oil", "oil", "", "", 0.0, None, "Toasted vs cold-pressed; nutty flavour; allergen; PUFA"),
    ("INS1608", "Flaxseed Oil (Linseed)", "oil", "", "", 0.0, None, "ALA omega-3 ~55%; heat sensitive; refrigerate; rancid fast"),
    ("INS1609", "Walnut Oil", "oil", "", "", 0.0, None, "Omega-3 ALA; nutty; cold-use only; pricey"),
    ("INS1610", "Butter (Cow's Milk)", "oil", "", "", 0.0, None, "Cream churned; 80% fat; saturated 50%; cholesterol; vitamin A"),
    ("INS1611", "Ghee / Clarified Butter", "oil", "", "", 0.0, None, "Milk solids removed; high smoke point; lactose-free; 99.5% fat"),
    ("INS1612", "Lard (Pork Fat)", "oil", "", "", 0.0, None, "Rendered pig fat; 40% saturated; high in vitamin D"),
    ("INS1613", "Margarine / Vegetable Spread", "oil", "", "", 0.0, None, "Hydrogenated plant oils; trans-fat free modern versions; spreadable"),
    ("INS1614", "Cocoa Butter", "oil", "", "", 0.0, None, "Theobroma cacao; chocolate fat; melt at body temp; saturated 60%"),
    ("INS1700", "Sodium Chloride (Table Salt)", "salt_sodium", "", "", 0.0, None, "NaCl; 40% Na; BP hypertension; iodized for goitre prevention"),
    ("INS1701", "Sea Salt", "salt_sodium", "", "", 0.0, None, "Evaporated seawater; same Na as table; trace minerals micro"),
    ("INS1702", "Himalayan Pink Salt", "salt_sodium", "", "", 0.0, None, "Pakistan rock salt; pink from iron; same 38-40% Na by weight"),
    ("INS1703", "Kosher Salt", "salt_sodium", "", "", 0.0, None, "Coarse flake; no additives; same sodium by weight; less dense"),
    ("INS1704", "Low Sodium Salt (Salt Substitute)", "salt_sodium", "", "", 0.0, None, "NaCl + KCl mixture (LoSalt etc); hypertension helpful"),
    ("INS1705", "Soy Sauce", "salt_sodium", "", "", 0.0, None, "Fermented soya; high sodium; umami; Kikkoman; light/dark types"),
    ("INS1706", "Fish Sauce (Nam Pla / Nuoc Mam)", "salt_sodium", "", "", 0.0, None, "Fermented anchovy; SE Asia; very salty + umami"),
    ("INS1707", "Worcestershire Sauce", "salt_sodium", "", "", 0.0, None, "Lea&Perrins; anchovies; tamarind; salt; umami"),
    ("INS1708", "Baking Soda (Sodium Bicarbonate)", "salt_sodium", "", "", 0.0, None, "NaHCO3; sodium 27% by weight; leavening; antacid"),
    ("INS1709", "Monosodium Glutamate (MSG-2)", "salt_sodium", "", "", 0.0, None, "Sodium salt; Na content 12%; add to total Na tally"),
    ("INS1710", "Sodium Benzoate-2", "salt_sodium", "", "", 0.0, None, "Preservative sodium; contribute to sodium count"),
]


class Command(BaseCommand):
    help = "Seed >= 100 common food additives into AdditiveReference"

    def handle(self, *args, **options):
        created = 0
        for code, name, cat, fssai, jecfa, adi, food_lim, notes in ADDITIVES:
            _, was_created = AdditiveReference.objects.get_or_create(
                code=code,
                defaults={
                    'common_name': name,
                    'category': cat,
                    'fssai_ref': fssai,
                    'who_jecfa_ref': jecfa,
                    'adi_mg_per_kg': adi,
                    'food_limit_mg_per_kg': food_lim,
                    'notes': notes,
                },
            )
            if was_created:
                created += 1

        total = AdditiveReference.objects.count()
        distinct = AdditiveReference.objects.values('code').distinct().count()
        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete: newly created={created}, total rows={total}, distinct codes={distinct}"
            )
        )
